[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.flip-link]
install_crate = { crate_name = "flip-link", binary = "flip-link", test_arg = ["-h"] }

[tasks.objcopy-central]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "central",
    "--",
    "-O",
    "ihex",
    "rmk-central.hex",
]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.objcopy-peripheral]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "peripheral",
    "--",
    "-O",
    "ihex",
    "rmk-peripheral.hex",
]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.objcopy-peripheral2]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "peripheral2",
    "--",
    "-O",
    "ihex",
    "rmk-peripheral2.hex",
]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.uf2-central]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "rmk-central.hex",
    "--output-path",
    "rmk-central.uf2",
    "--family",
    "nrf52840",
]
dependencies = ["objcopy-central"]

[tasks.uf2-peripheral]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "rmk-peripheral.hex",
    "--output-path",
    "rmk-peripheral.uf2",
    "--family",
    "nrf52840",
]
dependencies = ["objcopy-peripheral"]

[tasks.uf2-peripheral2]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "rmk-peripheral2.hex",
    "--output-path",
    "rmk-peripheral2.uf2",
    "--family",
    "nrf52840",
]
dependencies = ["objcopy-peripheral2"]

[tasks.uf2]
dependencies = ["uf2-central", "uf2-peripheral", "uf2-peripheral2"]

[tasks.mount-nicenano]
private = true
script = '''
if ! mountpoint -q /run/media/gbpagano/NICENANO; then
    udisksctl mount -b /dev/disk/by-label/NICENANO
fi
'''

[tasks.flash-left]
description = "Build and flash the left half"
dependencies = ["uf2-peripheral2", "mount-nicenano"]
command = "sudo"
args = ["cp", "rmk-peripheral2.uf2", "/run/media/gbpagano/NICENANO"]

[tasks.flash-central]
description = "Build and flash the central"
dependencies = ["uf2-central", "mount-nicenano"]
command = "sudo"
args = ["cp", "rmk-central.uf2", "/run/media/gbpagano/NICENANO"]

[tasks.flash-right]
description = "Build and flash the right half"
dependencies = ["uf2-peripheral", "mount-nicenano"]
command = "sudo"
args = ["cp", "rmk-peripheral.uf2", "/run/media/gbpagano/NICENANO"]
